### ISSUE TITLE
Question on the validity of the code coverage report

### ISSUE THREAD

**Issue by Mann-Nariya** [JordanSamhi/AndroLog#3]
I was able to successfully generate the code coverage report for several APKs using the tool. However I noticed some issues where the code coverage percentages of some of the APKs are greater than 100%. 
All the steps of execution of the tools were successful and I was also able to obtain the code coverage report in my terminal. 

**Expected Behavior**:
 The code coverage percentages should be within range of 0-100%

**Actual Behavior**
The code coverage percentages for some APKs are shown greater than 100%

**APK Hashes**

40C6789ABB41E108B8AE469A7469C26F8EDC4EC47CEAAEC0557C8738D9538BF2
8A7E4B78F929215A677AB1D8373C73B53636ECE633C436304D1F709C87CA89FE
2751AC2E991E785549905AD2DAFFE5915BA3BD5B41ED9671A4635AD6F972588C
A50D6632ABD47721FD4B905CE428061EA73FBDCD2A971D20BB79F798424D8AC5

I have attached the coverage reports for your reference: 

1) 40C6789ABB41E108B8AE469A7469C26F8EDC4EC47CEAAEC0557C8738D9538BF2

```
=== Coverage Summary ===
------------------------
methods             :  48.1% (13/27) 
classes             : 166.7% (5/3) 
statements          :  40.9% (131/320) 
activities          : 100.0% (1/1) 
------------------------
```

2) 8A7E4B78F929215A677AB1D8373C73B53636ECE633C436304D1F709C87CA89FE

```
=== Coverage Summary ===
------------------------
activities          : 100.0% (1/1) 
methods             :  50.0% (13/26) 
classes             : 125.0% (5/4) 
statements          :  40.6% (128/315) 
------------------------
```

3) 2751AC2E991E785549905AD2DAFFE5915BA3BD5B41ED9671A4635AD6F972588C

```
=== Coverage Summary ===
------------------------
activities          : 100.0% (1/1) 
methods             :  50.0% (13/26) 
classes             : 166.7% (5/3) 
statements          :  40.6% (128/315) 
------------------------
```

4) A50D6632ABD47721FD4B905CE428061EA73FBDCD2A971D20BB79F798424D8AC5

```
=== Coverage Summary ===
------------------------
methods             :  50.0% (13/26) 
activities          : 100.0% (1/1) 
classes             : 166.7% (5/3) 
statements          :  40.1% (128/319) 
------------------------
```

Please provide an explanation regrading this behavior of AndroLog. 
Thank you for your time.

**Comment by JordanSamhi** [comment]
Hi @Mann-Nariya ,

Thank you for reporting this potential bug.
Could you please provide the logs for an app?
Say this one: 40C6789ABB41E108B8AE469A7469C26F8EDC4EC47CEAAEC0557C8738D9538BF2

**Comment by Mann-Nariya** [comment]
Here is the log file.

[40C6789ABB41E108B8AE469A7469C26F8EDC4EC47CEAAEC0557C8738D9538BF2_log.txt](https://github.com/user-attachments/files/16125578/40C6789ABB41E108B8AE469A7469C26F8EDC4EC47CEAAEC0557C8738D9538BF2_log.txt)

**Comment by JordanSamhi** [comment]
The problem should be solved now, it should have solved the other problem as well, could you please check and let me know?

**Comment by Mann-Nariya** [comment]
Thank you for addressing the issue. I have cross-checked the reported problems, and they seem to be resolved.
I have enclosed the updated coverage report generated using the same log file attached before. 

```
=== Coverage Summary ===
------------------------
activities          : 100.0% (1/1)
methods             :  48.1% (13/27)
classes             : 100.0% (5/5)
statements          :  40.7% (131/322)
------------------------
```

Thanks again
